### ISSUE TITLE
Update your dependecies.. 

### ISSUE THREAD

**Issue by MarcKarasek** [marvinroger/node-binary-file#5]
When you try to install this under windows using current node/pm you get a warning.

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for binary-file@0.2.1: wanted: {"node":"^4.0.0"} (current: {"node":"12.13.1","npm":"6.12.1"})
npm WARN notsup Not compatible with your version of node/npm: binary-file@0.2.1

I did not notice if this same warning appears under linux (assume it does).
node v13.2.0
npm v6.13.1
And works fine under Linux

I thnk node 12.13.1 is greater than 4.0.0 LOL

**Comment by MarcKarasek** [comment]
BTW works fine under linux , will test on windows soon.

**Comment by marvinroger** [comment]
Fixed on `0.2.3`, thanks!
